version: "3"
services:
  db:
    build: ./initdb/
    expose:
      - 5432
  app:
    build: .
    depends_on:
        - db
    ports:
        - 8080:8080
    links:
        - db
    environment:
        - DB_URL=jdbc:postgresql://db:5432/task04
